import{ ContentType,Content } from "../type/contentType";

export const ieltsTopics = [
  "Environment",
  "Education",
  "Technology",
  "Health",
  "Work",
] as const;

export const ieltsBands = [5, 6, 7, 8, 9];

export const contentTypes : ContentType[] = [
  {type: "s", description: "Sentence"},
  {type: "p", description: "Paragraph"},
]
export const contents : Content[] = [
  {
    topic: ["Environment"],
    english: "Climate change is one of the most pressing issues of our time.",
    vietnamese: "Biến đổi khí hậu là một trong những vấn đề cấp bách nhất của thời đại chúng ta.",
    band: 6,
    type: "s",
  },
  {
    topic: ["Environment"],
    english: "Renewable energy sources are becoming increasingly important.",
    vietnamese: "Các nguồn năng lượng tái tạo đang trở nên ngày càng quan trọng.",
    band: 6,
    type: "s",
  },
  {
    topic: ["Education"],
    english: "Online learning has transformed the educational landscape.",
    vietnamese: "Học trực tuyến đã làm thay đổi bối cảnh giáo dục.",
    band: 6,
    type: "s",
  },
  {
    topic: ["Education"],
    english: "Critical thinking skills are essential in modern education.",
    vietnamese: "Kỹ năng tư duy phản biện là thiết yếu trong giáo dục hiện đại.",
    band: 7,
    type: "s",
  },
  {
    topic: ["Technology"],
    english: "Artificial intelligence is revolutionizing various industries.",
    vietnamese: "Trí tuệ nhân tạo đang cách mạng hóa nhiều ngành công nghiệp.",
    band: 7,
    type: "s",
  },
  {
    topic: ["Technology"],
    english: "The Internet of Things has connected our world like never before.",
    vietnamese: "Internet vạn vật đã kết nối thế giới của chúng ta như chưa từng có.",
    band: 8,
    type: "s",
  },
  {
    topic: ["health"],
    english: "Regular exercise is crucial for maintaining good health.",
    vietnamese: "Tập thể dục thường xuyên rất quan trọng để duy trì sức khỏe tốt.",
    band: 6,
    type: "s",
  },
  {
    topic: ["health"],
    english: "Mental health awareness has increased significantly in recent years.",
    vietnamese: "Nhận thức về sức khỏe tâm thần đã tăng lên đáng kể trong những năm gần đây.",
    band: 7,
    type: "s",
  },
  {
    topic: ["work"],
    english: "Remote work has become more common in many industries.",
    vietnamese: "Làm việc từ xa đã trở nên phổ biến hơn trong nhiều ngành công nghiệp.",
    band: 6,
    type: "s",
  },
  {
    topic: ["work"],
    english: "Work-life balance is an important factor in job satisfaction.",
    vietnamese: "Cân bằng công việc-cuộc sống là một yếu tố quan trọng trong sự hài lòng với công việc.",
    band: 7,
    type: "s",
  },
  {
    topic: ["Environment"],
    english: "Deforestation is a major concern for biodiversity.",
    vietnamese: "Nạn phá rừng là một mối lo ngại lớn đối với sự đa dạng sinh học.",
    band: 7,
    type: "s",
},
{
    topic: ["Education"],
    english: "The integration of technology into classrooms enhances student learning.",
    vietnamese: "Việc tích hợp công nghệ vào lớp học nâng cao khả năng học tập của học sinh.",
    band: 7,
    type: "s",
},
{
    topic: ["Technology"],
    english: "Blockchain technology has the potential to transform many sectors.",
    vietnamese: "Công nghệ blockchain có tiềm năng cách mạng hóa nhiều ngành.",
    band: 8,
    type: "s",
},
{
    topic: ["Health"],
    english: "Vaccination is a key measure in preventing the spread of infectious diseases.",
    vietnamese: "Tiêm chủng là một biện pháp quan trọng trong việc ngăn ngừa sự lây lan của các bệnh truyền nhiễm.",
    band: 6,
    type: "s",
},
{
    topic: ["Work"],
    english: "Flexible working hours can improve employee productivity and satisfaction.",
    vietnamese: "Giờ làm việc linh hoạt có thể cải thiện năng suất và sự hài lòng của nhân viên.",
    band: 6,
    type: "s",
},
{
    topic: ["Technology"],
    english: "Cloud computing has revolutionized the way businesses operate.",
    vietnamese: "Điện toán đám mây đã cách mạng hóa cách thức hoạt động của các doanh nghiệp.",
    band: 7,
    type: "s",
},
{
    topic: ["Health"],
    english: "Nutrition plays a vital role in maintaining overall health and wellness.",
    vietnamese: "Dinh dưỡng đóng vai trò quan trọng trong việc duy trì sức khỏe tổng thể và sự khỏe mạnh.",
    band: 6,
    type: "s",
},
{
    topic: ["Education"],
    english: "Standardized testing has been criticized for failing to measure student potential accurately.",
    vietnamese: "Các bài kiểm tra chuẩn hóa đã bị chỉ trích vì không thể đo lường chính xác tiềm năng của học sinh.",
    band: 7,
    type: "s",
},
{
    topic: ["Work"],
    english: "Job automation is reshaping the workforce, creating both opportunities and challenges.",
    vietnamese: "Tự động hóa công việc đang thay đổi lực lượng lao động, tạo ra cả cơ hội và thách thức.",
    band: 8,
    type: "s",
},
{
    topic: ["Environment"],
    english: "Reducing carbon emissions is crucial to mitigating the effects of climate change.",
    vietnamese: "Giảm phát thải carbon là yếu tố quan trọng để giảm thiểu tác động của biến đổi khí hậu.",
    band: 7,
    type: "s",
},
{
  topic: ["Environment"],
  english: `Climate change is having a profound impact on ecosystems around the world. Rising global temperatures are causing ice caps to melt, leading to rising sea levels. Extreme weather patterns such as hurricanes, droughts, and heatwaves are becoming more frequent, disrupting local communities and economies. Governments and organizations worldwide must take urgent action to reduce greenhouse gas emissions and promote sustainable practices to mitigate these effects. Renewable energy sources, such as wind, solar, and hydropower, offer a promising alternative to fossil fuels, helping to reduce the carbon footprint of industries and households alike.`,
  vietnamese: `Biến đổi khí hậu đang có ảnh hưởng sâu rộng đến các hệ sinh thái trên toàn cầu. Nhiệt độ toàn cầu tăng cao đang khiến các tảng băng tan chảy, dẫn đến mực nước biển dâng cao. Các hiện tượng thời tiết cực đoan như bão, hạn hán và sóng nhiệt đang trở nên thường xuyên hơn, gây xáo trộn cho các cộng đồng và nền kinh tế địa phương. Các chính phủ và tổ chức trên toàn thế giới cần hành động khẩn cấp để giảm khí thải nhà kính và thúc đẩy các thực hành bền vững để giảm thiểu những tác động này. Các nguồn năng lượng tái tạo như gió, mặt trời và thủy điện mang lại một giải pháp đầy triển vọng thay thế nhiên liệu hóa thạch, giúp giảm dấu chân carbon của các ngành công nghiệp và hộ gia đình.`,
  band: 8,
  type: "p",
},
{
  topic: ["Education"],
  english: `In the modern education system, technology has become an integral part of the learning process. Digital tools and online platforms offer students access to a wide range of resources, making learning more interactive and engaging. Teachers can incorporate multimedia elements such as videos, podcasts, and interactive quizzes into their lessons, enhancing the overall learning experience. Furthermore, online learning provides flexibility, allowing students to learn at their own pace and from the comfort of their homes. However, the digital divide remains a challenge, as not all students have equal access to technology.`,
  vietnamese: `Trong hệ thống giáo dục hiện đại, công nghệ đã trở thành một phần không thể thiếu trong quá trình học tập. Các công cụ số và nền tảng trực tuyến mang đến cho học sinh quyền truy cập vào một loạt các tài nguyên, giúp học tập trở nên tương tác và hấp dẫn hơn. Giáo viên có thể tích hợp các yếu tố đa phương tiện như video, podcast và câu đố tương tác vào bài giảng của mình, nâng cao trải nghiệm học tập tổng thể. Hơn nữa, học trực tuyến cung cấp tính linh hoạt, cho phép học sinh học theo tốc độ của riêng mình và từ sự thoải mái của ngôi nhà. Tuy nhiên, sự phân chia kỹ thuật số vẫn là một thách thức, vì không phải học sinh nào cũng có quyền truy cập công bằng vào công nghệ.`,
  band: 7,
  type: "p",
},
{
  topic: ["Health"],
  english: `Mental health is often overlooked in discussions about overall health and wellness, but it plays a crucial role in a person's well-being. Mental illnesses such as depression, anxiety, and stress can significantly impact daily life, making it difficult to work, socialize, and maintain healthy relationships. Early intervention and proper treatment are essential for managing these conditions and improving quality of life. Public awareness campaigns and education about mental health can help reduce stigma and encourage individuals to seek help when needed. Additionally, creating supportive environments at home, school, and work can foster better mental health for everyone.`,
  vietnamese: `Sức khỏe tâm thần thường bị bỏ qua trong các cuộc thảo luận về sức khỏe tổng thể và sự khỏe mạnh, nhưng nó đóng vai trò quan trọng trong phúc lợi của một người. Các bệnh tâm thần như trầm cảm, lo âu và căng thẳng có thể ảnh hưởng nghiêm trọng đến cuộc sống hàng ngày, khiến việc làm việc, giao tiếp xã hội và duy trì các mối quan hệ lành mạnh trở nên khó khăn. Can thiệp sớm và điều trị đúng cách là rất quan trọng để quản lý các tình trạng này và cải thiện chất lượng cuộc sống. Các chiến dịch nâng cao nhận thức công cộng và giáo dục về sức khỏe tâm thần có thể giúp giảm kỳ thị và khuyến khích cá nhân tìm kiếm sự giúp đỡ khi cần thiết. Hơn nữa, tạo ra các môi trường hỗ trợ tại nhà, trường học và nơi làm việc có thể thúc đẩy sức khỏe tâm thần tốt hơn cho mọi người.`,
  band: 7,
  type: "p",
},
{
  topic: ["Technology"],
  english: `The rapid development of artificial intelligence (AI) has transformed many industries, from healthcare to finance, and even entertainment. AI technologies such as machine learning, natural language processing, and computer vision are revolutionizing the way businesses operate and how services are delivered. In healthcare, AI is being used to analyze medical data, improve diagnostic accuracy, and even assist in surgery. In finance, AI is helping banks and financial institutions detect fraudulent transactions and predict market trends. As AI continues to evolve, its potential applications are boundless, but ethical concerns, such as job displacement and data privacy, must also be addressed.`,
  vietnamese: `Sự phát triển nhanh chóng của trí tuệ nhân tạo (AI) đã thay đổi nhiều ngành công nghiệp, từ chăm sóc sức khỏe đến tài chính, và thậm chí là giải trí. Các công nghệ AI như học máy, xử lý ngôn ngữ tự nhiên và thị giác máy tính đang cách mạng hóa cách thức hoạt động của các doanh nghiệp và cách thức dịch vụ được cung cấp. Trong chăm sóc sức khỏe, AI được sử dụng để phân tích dữ liệu y tế, cải thiện độ chính xác trong chẩn đoán và thậm chí hỗ trợ trong phẫu thuật. Trong tài chính, AI đang giúp các ngân hàng và tổ chức tài chính phát hiện giao dịch gian lận và dự đoán xu hướng thị trường. Khi AI tiếp tục phát triển, những ứng dụng tiềm năng của nó là vô hạn, nhưng các mối quan tâm về đạo đức, chẳng hạn như thay thế công việc và bảo mật dữ liệu, cũng phải được giải quyết.`,
  band: 8,
  type: "p",
},
{
  topic: ["Environment"],
  english: "Preserving forests is essential for combating climate change and protecting biodiversity.",
  vietnamese: "Bảo tồn rừng là cần thiết để chống lại biến đổi khí hậu và bảo vệ đa dạng sinh học.",
  band: 7,
  type: "s",
},
{
  topic: ["Education"],
  english: "Group projects can help students develop teamwork and communication skills.",
  vietnamese: "Các dự án nhóm có thể giúp học sinh phát triển kỹ năng làm việc nhóm và giao tiếp.",
  band: 6,
  type: "s",
},
{
  topic: ["Technology"],
  english: "Virtual reality is changing the way we experience education and entertainment.",
  vietnamese: "Thực tế ảo đang thay đổi cách chúng ta trải nghiệm giáo dục và giải trí.",
  band: 7,
  type: "s",
},
{
  topic: ["Health"],
  english: "A balanced diet and regular physical activity are the pillars of a healthy lifestyle.",
  vietnamese: "Một chế độ ăn uống cân đối và hoạt động thể chất thường xuyên là nền tảng của lối sống lành mạnh.",
  band: 6,
  type: "s",
},
{
  topic: ["Work"],
  english: "Effective communication in the workplace leads to better teamwork and productivity.",
  vietnamese: "Giao tiếp hiệu quả tại nơi làm việc dẫn đến sự hợp tác và năng suất tốt hơn.",
  band: 6,
  type: "s",
},
{
  topic: ["Environment"],
  english: "Promoting eco-friendly practices in daily life can significantly reduce waste.",
  vietnamese: "Thúc đẩy các thói quen thân thiện với môi trường trong cuộc sống hàng ngày có thể giảm đáng kể lượng rác thải.",
  band: 6,
  type: "s",
},
{
  topic: ["Education"],
  english: "Lifelong learning is essential in a rapidly changing world.",
  vietnamese: "Học tập suốt đời là rất cần thiết trong một thế giới đang thay đổi nhanh chóng.",
  band: 7,
  type: "s",
},
{
  topic: ["Technology"],
  english: "5G technology promises faster connectivity and new possibilities in various sectors.",
  vietnamese: "Công nghệ 5G hứa hẹn kết nối nhanh hơn và mang lại những khả năng mới trong nhiều lĩnh vực.",
  band: 8,
  type: "s",
},
{
  topic: ["Health"],
  english: "Proper sleep hygiene is vital for mental and physical health.",
  vietnamese: "Vệ sinh giấc ngủ đúng cách là rất quan trọng cho sức khỏe tinh thần và thể chất.",
  band: 7,
  type: "s",
},
{
  topic: ["Work"],
  english: "Diversity in the workplace can lead to more innovative ideas and solutions.",
  vietnamese: "Đa dạng tại nơi làm việc có thể mang lại những ý tưởng và giải pháp sáng tạo hơn.",
  band: 7,
  type: "s",
},
{
  topic: ["Environment"],
  english: `Plastic pollution is one of the most pervasive environmental issues of our time. Millions of tons of plastic waste are generated each year, much of which ends up in oceans, harming marine life and ecosystems. Reducing single-use plastics and promoting recycling programs are crucial steps toward addressing this crisis. Public awareness campaigns and stricter regulations on plastic production and disposal can also play a significant role in mitigating the impact of plastic pollution.`,
  vietnamese: `Ô nhiễm nhựa là một trong những vấn đề môi trường phổ biến nhất của thời đại chúng ta. Hàng triệu tấn rác thải nhựa được tạo ra mỗi năm, nhiều trong số đó kết thúc ở đại dương, gây hại cho động vật biển và hệ sinh thái. Việc giảm sử dụng nhựa một lần và thúc đẩy các chương trình tái chế là những bước quan trọng để giải quyết khủng hoảng này. Các chiến dịch nâng cao nhận thức công cộng và quy định nghiêm ngặt hơn về sản xuất và xử lý nhựa cũng có thể đóng vai trò quan trọng trong việc giảm thiểu tác động của ô nhiễm nhựa.`,
  band: 7,
  type: "p",
},
{
  topic: ["Education"],
  english: `Project-based learning is an innovative approach to education that focuses on hands-on experiences and real-world applications. Students work collaboratively on projects that require critical thinking, problem-solving, and creativity. This method not only enhances understanding but also prepares students for the challenges of the modern workplace. However, effective implementation requires well-trained teachers and access to sufficient resources.`,
  vietnamese: `Học tập dựa trên dự án là một cách tiếp cận giáo dục sáng tạo tập trung vào trải nghiệm thực tế và ứng dụng thực tiễn. Học sinh làm việc hợp tác trên các dự án đòi hỏi tư duy phản biện, giải quyết vấn đề và sáng tạo. Phương pháp này không chỉ nâng cao hiểu biết mà còn chuẩn bị cho học sinh đối mặt với các thách thức của nơi làm việc hiện đại. Tuy nhiên, để thực hiện hiệu quả cần có giáo viên được đào tạo tốt và tiếp cận đầy đủ các nguồn lực.`,
  band: 6,
  type: "p",
},
{
  topic: ["Technology"],
  english: `The rise of e-commerce has revolutionized the retail industry, offering convenience and accessibility to consumers worldwide. Platforms like Amazon and Alibaba provide a vast array of products at competitive prices, often delivered to customers' doorsteps within days. However, the growth of e-commerce has also led to challenges, including increased packaging waste, carbon emissions from delivery services, and the decline of brick-and-mortar stores.`,
  vietnamese: `Sự phát triển của thương mại điện tử đã cách mạng hóa ngành bán lẻ, mang lại sự tiện lợi và khả năng tiếp cận cho người tiêu dùng trên toàn thế giới. Các nền tảng như Amazon và Alibaba cung cấp một loạt các sản phẩm với giá cả cạnh tranh, thường được giao đến tận nhà của khách hàng trong vòng vài ngày. Tuy nhiên, sự phát triển của thương mại điện tử cũng dẫn đến các thách thức như rác thải đóng gói gia tăng, khí thải carbon từ các dịch vụ giao hàng và sự suy giảm của các cửa hàng truyền thống.`,
  band: 7,
  type: "p",
},
{
  topic: ["Health"],
  english: `The growing popularity of fitness tracking devices highlights the increasing awareness of health and wellness. These devices monitor physical activities, heart rate, and sleep patterns, encouraging individuals to maintain a healthier lifestyle. The integration of technology into health monitoring has the potential to prevent chronic diseases and improve overall well-being. However, concerns about data privacy and accuracy must be addressed to maximize their benefits.`,
  vietnamese: `Sự phổ biến ngày càng tăng của các thiết bị theo dõi sức khỏe nhấn mạnh nhận thức ngày càng cao về sức khỏe và sự khỏe mạnh. Những thiết bị này theo dõi hoạt động thể chất, nhịp tim và giấc ngủ, khuyến khích mọi người duy trì một lối sống lành mạnh hơn. Việc tích hợp công nghệ vào giám sát sức khỏe có tiềm năng ngăn ngừa các bệnh mãn tính và cải thiện sức khỏe tổng thể. Tuy nhiên, các mối quan tâm về bảo mật dữ liệu và độ chính xác cần được giải quyết để tối ưu hóa lợi ích của chúng.`,
  band: 8,
  type: "p",
},
{
  topic: ["Work"],
  english: `The gig economy has significantly altered the traditional job market, providing flexible work opportunities to millions of individuals. Platforms such as Uber, Upwork, and Fiverr allow workers to take on projects or tasks on a freelance basis, offering greater control over their schedules. While this model offers independence, it also raises issues such as job security, benefits, and worker protection.`,
  vietnamese: `Nền kinh tế gig đã thay đổi đáng kể thị trường lao động truyền thống, mang lại cơ hội làm việc linh hoạt cho hàng triệu người. Các nền tảng như Uber, Upwork và Fiverr cho phép người lao động nhận các dự án hoặc nhiệm vụ theo hình thức tự do, mang lại sự kiểm soát tốt hơn đối với lịch trình của họ. Trong khi mô hình này mang lại sự độc lập, nó cũng đặt ra các vấn đề như an ninh công việc, phúc lợi và bảo vệ người lao động.`,
  band: 7,
  type: "p",
},
{
  topic: ["Work"],
  english: `Team collaboration is a cornerstone of success in modern workplaces. Effective communication and teamwork enable employees to share ideas, solve problems, and achieve common goals more efficiently. Many organizations are adopting collaborative tools such as Slack, Microsoft Teams, and Trello to streamline workflows and enhance productivity. However, fostering a collaborative culture requires strong leadership and a commitment to inclusivity.`,
  vietnamese: `Sự hợp tác trong nhóm là nền tảng của thành công trong các nơi làm việc hiện đại. Giao tiếp hiệu quả và làm việc nhóm cho phép nhân viên chia sẻ ý tưởng, giải quyết vấn đề và đạt được các mục tiêu chung một cách hiệu quả hơn. Nhiều tổ chức đang áp dụng các công cụ cộng tác như Slack, Microsoft Teams và Trello để tối ưu hóa quy trình làm việc và nâng cao năng suất. Tuy nhiên, xây dựng một văn hóa hợp tác đòi hỏi sự lãnh đạo mạnh mẽ và cam kết về tính bao trùm.`,
  band: 7,
  type: "p",
},
{
  topic: ["Work"],
  english: `Employee well-being has become a top priority for organizations aiming to retain talent and boost performance. Companies are increasingly offering wellness programs, mental health resources, and flexible working options to support their workforce. Research shows that happier employees are more engaged and productive, creating a win-win situation for both employers and workers. However, implementing these initiatives effectively requires thoughtful planning and regular feedback.`,
  vietnamese: `Sức khỏe của nhân viên đã trở thành ưu tiên hàng đầu của các tổ chức nhằm giữ chân nhân tài và nâng cao hiệu suất. Các công ty ngày càng cung cấp các chương trình chăm sóc sức khỏe, nguồn tài nguyên về sức khỏe tinh thần và các lựa chọn làm việc linh hoạt để hỗ trợ lực lượng lao động của họ. Nghiên cứu cho thấy rằng nhân viên hạnh phúc hơn sẽ gắn bó và làm việc hiệu quả hơn, tạo ra một tình huống đôi bên cùng có lợi cho cả nhà tuyển dụng và người lao động. Tuy nhiên, việc triển khai các sáng kiến này một cách hiệu quả đòi hỏi sự lập kế hoạch cẩn thận và phản hồi thường xuyên.`,
  band: 8,
  type: "p",
},
{
  topic: ["Work"],
  english: `Team collaboration is a cornerstone of success in modern workplaces. Effective communication and teamwork enable employees to share ideas, solve problems, and achieve common goals more efficiently. Many organizations are adopting collaborative tools such as Slack, Microsoft Teams, and Trello to streamline workflows and enhance productivity. However, fostering a collaborative culture requires strong leadership and a commitment to inclusivity.`,
  vietnamese: `Sự hợp tác trong nhóm là nền tảng của thành công trong các nơi làm việc hiện đại. Giao tiếp hiệu quả và làm việc nhóm cho phép nhân viên chia sẻ ý tưởng, giải quyết vấn đề và đạt được các mục tiêu chung một cách hiệu quả hơn. Nhiều tổ chức đang áp dụng các công cụ cộng tác như Slack, Microsoft Teams và Trello để tối ưu hóa quy trình làm việc và nâng cao năng suất. Tuy nhiên, xây dựng một văn hóa hợp tác đòi hỏi sự lãnh đạo mạnh mẽ và cam kết về tính bao trùm.`,
  band: 8,
  type: "p",
},
];
