import{ ContentType,Content } from "../type/contentType";

export const ieltsTopics = [
  "Environment",
  "Education",
  "Technology",
  "Health",
  "Work",
] as const;

export const ieltsBands = [5, 6, 7, 8, 9];

export const contentTypes : ContentType[] = [
  {type: "s", description: "Sentence"},
  {type: "p", description: "Paragraph"},
]
export const contents : Content[] = [
  {
    topic: ["Environment"],
    english: "Climate change is one of the most pressing issues of our time.",
    vietnamese: "Biến đổi khí hậu là một trong những vấn đề cấp bách nhất của thời đại chúng ta.",
    band: 6,
    type: "s",
  },
  {
    topic: ["Environment"],
    english: "Renewable energy sources are becoming increasingly important.",
    vietnamese: "Các nguồn năng lượng tái tạo đang trở nên ngày càng quan trọng.",
    band: 6,
    type: "s",
  },
  {
    topic: ["Education"],
    english: "Online learning has transformed the educational landscape.",
    vietnamese: "Học trực tuyến đã làm thay đổi bối cảnh giáo dục.",
    band: 6,
    type: "s",
  },
  {
    topic: ["Education"],
    english: "Critical thinking skills are essential in modern education.",
    vietnamese: "Kỹ năng tư duy phản biện là thiết yếu trong giáo dục hiện đại.",
    band: 7,
    type: "s",
  },
  {
    topic: ["Technology"],
    english: "Artificial intelligence is revolutionizing various industries.",
    vietnamese: "Trí tuệ nhân tạo đang cách mạng hóa nhiều ngành công nghiệp.",
    band: 7,
    type: "s",
  },
  {
    topic: ["Technology"],
    english: "The Internet of Things has connected our world like never before.",
    vietnamese: "Internet vạn vật đã kết nối thế giới của chúng ta như chưa từng có.",
    band: 8,
    type: "s",
  },
  {
    topic: ["health"],
    english: "Regular exercise is crucial for maintaining good health.",
    vietnamese: "Tập thể dục thường xuyên rất quan trọng để duy trì sức khỏe tốt.",
    band: 6,
    type: "s",
  },
  {
    topic: ["health"],
    english: "Mental health awareness has increased significantly in recent years.",
    vietnamese: "Nhận thức về sức khỏe tâm thần đã tăng lên đáng kể trong những năm gần đây.",
    band: 7,
    type: "s",
  },
  {
    topic: ["work"],
    english: "Remote work has become more common in many industries.",
    vietnamese: "Làm việc từ xa đã trở nên phổ biến hơn trong nhiều ngành công nghiệp.",
    band: 6,
    type: "s",
  },
  {
    topic: ["work"],
    english: "Work-life balance is an important factor in job satisfaction.",
    vietnamese: "Cân bằng công việc-cuộc sống là một yếu tố quan trọng trong sự hài lòng với công việc.",
    band: 7,
    type: "s",
  },
  {
    topic: ["Environment"],
    english: "Deforestation is a major concern for biodiversity.",
    vietnamese: "Nạn phá rừng là một mối lo ngại lớn đối với sự đa dạng sinh học.",
    band: 7,
    type: "s",
},
{
    topic: ["Education"],
    english: "The integration of technology into classrooms enhances student learning.",
    vietnamese: "Việc tích hợp công nghệ vào lớp học nâng cao khả năng học tập của học sinh.",
    band: 7,
    type: "s",
},
{
    topic: ["Technology"],
    english: "Blockchain technology has the potential to transform many sectors.",
    vietnamese: "Công nghệ blockchain có tiềm năng cách mạng hóa nhiều ngành.",
    band: 8,
    type: "s",
},
{
    topic: ["Health"],
    english: "Vaccination is a key measure in preventing the spread of infectious diseases.",
    vietnamese: "Tiêm chủng là một biện pháp quan trọng trong việc ngăn ngừa sự lây lan của các bệnh truyền nhiễm.",
    band: 6,
    type: "s",
},
{
    topic: ["Work"],
    english: "Flexible working hours can improve employee productivity and satisfaction.",
    vietnamese: "Giờ làm việc linh hoạt có thể cải thiện năng suất và sự hài lòng của nhân viên.",
    band: 6,
    type: "s",
},
{
    topic: ["Technology"],
    english: "Cloud computing has revolutionized the way businesses operate.",
    vietnamese: "Điện toán đám mây đã cách mạng hóa cách thức hoạt động của các doanh nghiệp.",
    band: 7,
    type: "s",
},
{
    topic: ["Health"],
    english: "Nutrition plays a vital role in maintaining overall health and wellness.",
    vietnamese: "Dinh dưỡng đóng vai trò quan trọng trong việc duy trì sức khỏe tổng thể và sự khỏe mạnh.",
    band: 6,
    type: "s",
},
{
    topic: ["Education"],
    english: "Standardized testing has been criticized for failing to measure student potential accurately.",
    vietnamese: "Các bài kiểm tra chuẩn hóa đã bị chỉ trích vì không thể đo lường chính xác tiềm năng của học sinh.",
    band: 7,
    type: "s",
},
{
    topic: ["Work"],
    english: "Job automation is reshaping the workforce, creating both opportunities and challenges.",
    vietnamese: "Tự động hóa công việc đang thay đổi lực lượng lao động, tạo ra cả cơ hội và thách thức.",
    band: 8,
    type: "s",
},
{
    topic: ["Environment"],
    english: "Reducing carbon emissions is crucial to mitigating the effects of climate change.",
    vietnamese: "Giảm phát thải carbon là yếu tố quan trọng để giảm thiểu tác động của biến đổi khí hậu.",
    band: 7,
    type: "s",
},
{
  topic: ["Environment"],
  english: `Climate change is having a profound impact on ecosystems around the world. Rising global temperatures are causing ice caps to melt, leading to rising sea levels. Extreme weather patterns such as hurricanes, droughts, and heatwaves are becoming more frequent, disrupting local communities and economies. Governments and organizations worldwide must take urgent action to reduce greenhouse gas emissions and promote sustainable practices to mitigate these effects. Renewable energy sources, such as wind, solar, and hydropower, offer a promising alternative to fossil fuels, helping to reduce the carbon footprint of industries and households alike.`,
  vietnamese: `Biến đổi khí hậu đang có ảnh hưởng sâu rộng đến các hệ sinh thái trên toàn cầu. Nhiệt độ toàn cầu tăng cao đang khiến các tảng băng tan chảy, dẫn đến mực nước biển dâng cao. Các hiện tượng thời tiết cực đoan như bão, hạn hán và sóng nhiệt đang trở nên thường xuyên hơn, gây xáo trộn cho các cộng đồng và nền kinh tế địa phương. Các chính phủ và tổ chức trên toàn thế giới cần hành động khẩn cấp để giảm khí thải nhà kính và thúc đẩy các thực hành bền vững để giảm thiểu những tác động này. Các nguồn năng lượng tái tạo như gió, mặt trời và thủy điện mang lại một giải pháp đầy triển vọng thay thế nhiên liệu hóa thạch, giúp giảm dấu chân carbon của các ngành công nghiệp và hộ gia đình.`,
  band: 8,
  type: "p",
},
{
  topic: ["Education"],
  english: `In the modern education system, technology has become an integral part of the learning process. Digital tools and online platforms offer students access to a wide range of resources, making learning more interactive and engaging. Teachers can incorporate multimedia elements such as videos, podcasts, and interactive quizzes into their lessons, enhancing the overall learning experience. Furthermore, online learning provides flexibility, allowing students to learn at their own pace and from the comfort of their homes. However, the digital divide remains a challenge, as not all students have equal access to technology.`,
  vietnamese: `Trong hệ thống giáo dục hiện đại, công nghệ đã trở thành một phần không thể thiếu trong quá trình học tập. Các công cụ số và nền tảng trực tuyến mang đến cho học sinh quyền truy cập vào một loạt các tài nguyên, giúp học tập trở nên tương tác và hấp dẫn hơn. Giáo viên có thể tích hợp các yếu tố đa phương tiện như video, podcast và câu đố tương tác vào bài giảng của mình, nâng cao trải nghiệm học tập tổng thể. Hơn nữa, học trực tuyến cung cấp tính linh hoạt, cho phép học sinh học theo tốc độ của riêng mình và từ sự thoải mái của ngôi nhà. Tuy nhiên, sự phân chia kỹ thuật số vẫn là một thách thức, vì không phải học sinh nào cũng có quyền truy cập công bằng vào công nghệ.`,
  band: 7,
  type: "p",
},
{
  topic: ["Health"],
  english: `Mental health is often overlooked in discussions about overall health and wellness, but it plays a crucial role in a person's well-being. Mental illnesses such as depression, anxiety, and stress can significantly impact daily life, making it difficult to work, socialize, and maintain healthy relationships. Early intervention and proper treatment are essential for managing these conditions and improving quality of life. Public awareness campaigns and education about mental health can help reduce stigma and encourage individuals to seek help when needed. Additionally, creating supportive environments at home, school, and work can foster better mental health for everyone.`,
  vietnamese: `Sức khỏe tâm thần thường bị bỏ qua trong các cuộc thảo luận về sức khỏe tổng thể và sự khỏe mạnh, nhưng nó đóng vai trò quan trọng trong phúc lợi của một người. Các bệnh tâm thần như trầm cảm, lo âu và căng thẳng có thể ảnh hưởng nghiêm trọng đến cuộc sống hàng ngày, khiến việc làm việc, giao tiếp xã hội và duy trì các mối quan hệ lành mạnh trở nên khó khăn. Can thiệp sớm và điều trị đúng cách là rất quan trọng để quản lý các tình trạng này và cải thiện chất lượng cuộc sống. Các chiến dịch nâng cao nhận thức công cộng và giáo dục về sức khỏe tâm thần có thể giúp giảm kỳ thị và khuyến khích cá nhân tìm kiếm sự giúp đỡ khi cần thiết. Hơn nữa, tạo ra các môi trường hỗ trợ tại nhà, trường học và nơi làm việc có thể thúc đẩy sức khỏe tâm thần tốt hơn cho mọi người.`,
  band: 7,
  type: "p",
},
{
  topic: ["Technology"],
  english: `The rapid development of artificial intelligence (AI) has transformed many industries, from healthcare to finance, and even entertainment. AI technologies such as machine learning, natural language processing, and computer vision are revolutionizing the way businesses operate and how services are delivered. In healthcare, AI is being used to analyze medical data, improve diagnostic accuracy, and even assist in surgery. In finance, AI is helping banks and financial institutions detect fraudulent transactions and predict market trends. As AI continues to evolve, its potential applications are boundless, but ethical concerns, such as job displacement and data privacy, must also be addressed.`,
  vietnamese: `Sự phát triển nhanh chóng của trí tuệ nhân tạo (AI) đã thay đổi nhiều ngành công nghiệp, từ chăm sóc sức khỏe đến tài chính, và thậm chí là giải trí. Các công nghệ AI như học máy, xử lý ngôn ngữ tự nhiên và thị giác máy tính đang cách mạng hóa cách thức hoạt động của các doanh nghiệp và cách thức dịch vụ được cung cấp. Trong chăm sóc sức khỏe, AI được sử dụng để phân tích dữ liệu y tế, cải thiện độ chính xác trong chẩn đoán và thậm chí hỗ trợ trong phẫu thuật. Trong tài chính, AI đang giúp các ngân hàng và tổ chức tài chính phát hiện giao dịch gian lận và dự đoán xu hướng thị trường. Khi AI tiếp tục phát triển, những ứng dụng tiềm năng của nó là vô hạn, nhưng các mối quan tâm về đạo đức, chẳng hạn như thay thế công việc và bảo mật dữ liệu, cũng phải được giải quyết.`,
  band: 8,
  type: "p",
},
];
